
package view;

import control.Controller;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import model.Bitcoin;
import model.Ethereum;
import model.Investidor;
import model.Real;
import model.Ripple;

/**
 *
 * @author marjo
 */
public class Consultar extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaFrame
     */
    public Consultar(Investidor investidor,int i, Real real, Ethereum eth, Bitcoin btc, Ripple xrp) {
        initComponents();
        controller = new Controller(this, investidor);
        if ( i == 1){
            LBLtipo.setText("Cotação");
            controller.atualizarCotacao(btc, eth, xrp);
        } else if ( i == 2){
            LBLtipo.setText("Saldo");
            controller.Saldo(investidor);
        } else if ( i == 3){
            LBLtipo.setText("Extrato");
            controller.transacoes(investidor);
        } else {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLtipo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTexibir = new javax.swing.JTextArea();
        BTvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLtipo.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        LBLtipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLtipo.setText("tipo");

        TXTexibir.setColumns(20);
        TXTexibir.setRows(5);
        jScrollPane1.setViewportView(TXTexibir);

        BTvoltar.setText("RETURN");
        BTvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTvoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(LBLtipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTvoltar)
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LBLtipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTvoltar)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTvoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BTvoltarActionPerformed

 

    public JLabel getLBLtipo() {
        return LBLtipo;
    }

    public void setLBLtipo(JLabel LBLtipo) {
        this.LBLtipo = LBLtipo;
    }

    public JTextArea getTXTexibir() {
        return TXTexibir;
    }

    public void setTXTexibir(JTextArea TXTexibir) {
        this.TXTexibir = TXTexibir;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

  

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }
    
    private Controller controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTvoltar;
    private javax.swing.JLabel LBLtipo;
    private javax.swing.JTextArea TXTexibir;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
