
package view;

import control.Controller;
import control.ControllerCrypto;
import control.ControllerUsuario;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.Investidor;

/**
 *
 * @author marjo
 */
public class Menu extends javax.swing.JFrame {
//    int id; 
//    id = investidor.getID_user;
    /**
     * Creates new form Menu
     * @param investidor
     */
    Investidor investidor;

    public Investidor getInvestidor() {
        return investidor;
    }

    public void setInvestidor(Investidor investidor) {
        this.investidor = investidor;
    }
    
    public Menu(Investidor investidor) {
        initComponents();
        //Moedas moedas = Moedas();
        
        setInvestidor(investidor);
        
        control = new Controller(investidor);
        //control = new ControllerUsuario(this, investidor);
        //control2 = new ControllerCrypto(this, moedas)
        LBLnome.setText(investidor.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLnome = new javax.swing.JLabel();
        BTsaldo = new javax.swing.JButton();
        BTextrato = new javax.swing.JButton();
        BTsacar = new javax.swing.JButton();
        BTdeposito = new javax.swing.JButton();
        BTvender = new javax.swing.JButton();
        BTcomprar = new javax.swing.JButton();
        BTatualizar = new javax.swing.JButton();
        BTsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BEM VINDO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell Extra Bold", 1, 12))); // NOI18N

        LBLnome.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        LBLnome.setText("nome");

        BTsaldo.setText("Saldo");
        BTsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsaldoActionPerformed(evt);
            }
        });

        BTextrato.setText("Extrato");
        BTextrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTextratoActionPerformed(evt);
            }
        });

        BTsacar.setText("Sacar");
        BTsacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsacarActionPerformed(evt);
            }
        });

        BTdeposito.setText("Depositar");
        BTdeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTdepositoActionPerformed(evt);
            }
        });

        BTvender.setText("Vender");
        BTvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTvenderActionPerformed(evt);
            }
        });

        BTcomprar.setText("Comprar");
        BTcomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcomprarActionPerformed(evt);
            }
        });

        BTatualizar.setText("Atualizar");
        BTatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTatualizarActionPerformed(evt);
            }
        });

        BTsair.setText("Sair");
        BTsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTatualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTvender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTdeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTextrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTsacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTcomprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTsair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLnome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LBLnome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTsaldo)
                    .addComponent(BTextrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTsacar)
                    .addComponent(BTdeposito, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTcomprar)
                    .addComponent(BTvender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTatualizar)
                    .addComponent(BTsair))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTcomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcomprarActionPerformed
        // TODO add your handling code here:
        new Transacao(investidor, 1).setVisible(true);
    }//GEN-LAST:event_BTcomprarActionPerformed

    private void BTsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsaldoActionPerformed

        // TODO add your handling code here:
//        new Consultar(2).setVisible(true);
        new Senha(investidor, 1).setVisible(true);
    //controller.
    }//GEN-LAST:event_BTsaldoActionPerformed

    private void BTextratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTextratoActionPerformed
        // TODO add your handling code here:
        new Consultar(investidor, 3).setVisible(true);
    }//GEN-LAST:event_BTextratoActionPerformed

    private void BTdepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTdepositoActionPerformed
        // TODO add your handling code here:
        new Movimentar(investidor, 1).setVisible(true);
    }//GEN-LAST:event_BTdepositoActionPerformed

    private void BTsacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsacarActionPerformed
        // TODO add your handling code here:
        new Movimentar(investidor, 2).setVisible(true);
    }//GEN-LAST:event_BTsacarActionPerformed

    private void BTvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTvenderActionPerformed
        // TODO add your handling code here:
        new Transacao(investidor, 2).setVisible(true);
    }//GEN-LAST:event_BTvenderActionPerformed

    private void BTatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTatualizarActionPerformed
        // TODO add your handling code here:
        new Consultar(investidor, 1).setVisible(true);
    }//GEN-LAST:event_BTatualizarActionPerformed

    private void BTsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsairActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_BTsairActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }

    public JButton getBTatualizar() {
        return BTatualizar;
    }

    public void setBTatualizar(JButton BTatualizar) {
        this.BTatualizar = BTatualizar;
    }

    public JButton getBTcomprar() {
        return BTcomprar;
    }

    public void setBTcomprar(JButton BTcomprar) {
        this.BTcomprar = BTcomprar;
    }

    public JButton getBTdeposito() {
        return BTdeposito;
    }

    public void setBTdeposito(JButton BTdeposito) {
        this.BTdeposito = BTdeposito;
    }

    public JButton getBTextrato() {
        return BTextrato;
    }

    public void setBTextrato(JButton BTextrato) {
        this.BTextrato = BTextrato;
    }

    public JButton getBTsacar() {
        return BTsacar;
    }

    public void setBTsacar(JButton BTsacar) {
        this.BTsacar = BTsacar;
    }

    public JButton getBTsair() {
        return BTsair;
    }

    public void setBTsair(JButton BTsair) {
        this.BTsair = BTsair;
    }

    public JButton getBTsaldo() {
        return BTsaldo;
    }

    public void setBTsaldo(JButton BTsaldo) {
        this.BTsaldo = BTsaldo;
    }

    public JButton getBTvender() {
        return BTvender;
    }

    public void setBTvender(JButton BTvender) {
        this.BTvender = BTvender;
    }

    public JLabel getLBLnome() {
        return LBLnome;
    }

    public void setLBLnome(JLabel LBLnome) {
        this.LBLnome = LBLnome;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }
    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }
    
    private Controller control;
    //private ControllerUsuario control;
    //private ControllerCrypto control2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTatualizar;
    private javax.swing.JButton BTcomprar;
    private javax.swing.JButton BTdeposito;
    private javax.swing.JButton BTextrato;
    private javax.swing.JButton BTsacar;
    private javax.swing.JButton BTsair;
    private javax.swing.JButton BTsaldo;
    private javax.swing.JButton BTvender;
    private javax.swing.JLabel LBLnome;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
