
package view;

import control.Controller;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Bitcoin;
import model.Ethereum;
import model.Investidor;
import model.Real;
import model.Ripple;

/**
 * Representa a tela de confirmação de senha do sistema de investimento.
 * 
 * Esta classe exibe uma tela para o investidor confirmar sua senha antes de prosseguir com a transação.
 * Ela recebe informações como o investidor, o tipo de janela (para fins de controle interno), 
 * o tipo de transação (compra ou venda), instâncias das classes Real, Ethereum, Bitcoin e Ripple, 
 * e permite que o investidor digite a senha. Ao clicar em "OK", a senha informada é enviada 
 * ao controlador para validação.
 *
 * @author Marjorie Luize Martins Costa
 */
public class Senha extends javax.swing.JFrame {
    Investidor investidor;
    int janela;
    int tipo;
    Real real;
    Bitcoin btc;
    Ethereum eth;
    Ripple xrp;

    public Real getReal() {
        return real;
    }

    public void setReal(Real real) {
        this.real = real;
    }

    public Bitcoin getBtc() {
        return btc;
    }

    public void setBtc(Bitcoin btc) {
        this.btc = btc;
    }

    public Ethereum getEth() {
        return eth;
    }

    public void setEth(Ethereum eth) {
        this.eth = eth;
    }

    public Ripple getXrp() {
        return xrp;
    }

    public void setXrp(Ripple xrp) {
        this.xrp = xrp;
    }
    public int getTipo() {
        return tipo;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    public Investidor getInvestidor() {
        return investidor;
    }

    public void setInvestidor(Investidor investidor) {
        this.investidor = investidor;
    }

    public int getJanela() {
        return janela;
    }

    public void setJanela(int janela) {
        this.janela = janela;
    }
    /**
     * Creates new form Senha
     */
    
    /**
   * Construtor da classe Senha.
   * 
   * Este construtor recebe as informações necessárias para inicializar a tela:
   * investidor - Investidor realizando a transação.
   * j - Tipo da janela (para controle interno).
   * t - Tipo de transação (compra ou venda).
   * real - Instância da classe Real.
   * eth - Instância da classe Ethereum.
   * btc - Instância da classe Bitcoin.
   * xrp - Instância da classe Ripple.
   * 
   * Inicializa os componentes visuais da tela e armazena as informações passadas como parâmetros.
   * Cria uma instância do controlador e o associa à tela.
   * 
   * @param investidor Investidor realizando a transação.
   * @param j Tipo da janela (para controle interno).
   * @param t Tipo de transação (compra ou venda).
   * @param real Instância da classe Real.
   * @param eth Instância da classe Ethereum.
   * @param btc Instância da classe Bitcoin.
   * @param xrp Instância da classe Ripple.
   */
    public Senha(Investidor investidor,int j, int t, Real real, Ethereum eth, Bitcoin btc, Ripple xrp) {
        initComponents();
        
        controller = new Controller(this, investidor);
        setJanela(j);
        setTipo(t);
        setInvestidor(investidor);
        setXrp(xrp);
        setReal(real);
        setBtc(btc);
        setEth(eth);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BTsenha = new javax.swing.JButton();
        TXTsenha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BTsenha.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        BTsenha.setText("OK");
        BTsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsenhaActionPerformed(evt);
            }
        });

        TXTsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTsenhaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel1.setText("Senha:");

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        jLabel3.setText("CONFIRMAÇÃO");

        jButton1.setText("RETURN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTsenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(TXTsenha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTsenha)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsenhaActionPerformed
        
        controller.Validar(investidor, janela, tipo, real, eth, btc, xrp);
    }//GEN-LAST:event_BTsenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TXTsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTsenhaActionPerformed
       
    }//GEN-LAST:event_TXTsenhaActionPerformed

 


    public JButton getBTsenha() {
        return BTsenha;
    }

    public void setBTsenha(JButton BTsenha) {
        this.BTsenha = BTsenha;
    }

    public JTextField getTXTsenha() {
        return TXTsenha;
    }

    public void setTXTsenha(JTextField TXTsenha) {
        this.TXTsenha = TXTsenha;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

 

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }
    
    private Controller controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTsenha;
    private javax.swing.JTextField TXTsenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
